# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadsettings.ui'
#
# Created: Fri Oct 15 17:32:20 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CadSettings(object):
    def setupUi(self, CadSettings):
        CadSettings.setObjectName("CadSettings")
        CadSettings.resize(408, 284)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CadSettings.sizePolicy().hasHeightForWidth())
        CadSettings.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(CadSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtGui.QDialogButtonBox(CadSettings)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(CadSettings)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tabCurves = QtGui.QWidget()
        self.tabCurves.setObjectName("tabCurves")
        self.gridLayout_2 = QtGui.QGridLayout(self.tabCurves)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtGui.QGroupBox(self.tabCurves)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioFeaturePitch = QtGui.QRadioButton(self.groupBox)
        self.radioFeaturePitch.setChecked(True)
        self.radioFeaturePitch.setObjectName("radioFeaturePitch")
        self.horizontalLayout.addWidget(self.radioFeaturePitch)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spinBoxFeaturePitch = QtGui.QDoubleSpinBox(self.groupBox)
        self.spinBoxFeaturePitch.setEnabled(True)
        self.spinBoxFeaturePitch.setDecimals(1)
        self.spinBoxFeaturePitch.setMaximum(100.0)
        self.spinBoxFeaturePitch.setProperty("value", 2.0)
        self.spinBoxFeaturePitch.setObjectName("spinBoxFeaturePitch")
        self.horizontalLayout.addWidget(self.spinBoxFeaturePitch)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioFeatureAngle = QtGui.QRadioButton(self.groupBox)
        self.radioFeatureAngle.setObjectName("radioFeatureAngle")
        self.horizontalLayout_2.addWidget(self.radioFeatureAngle)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.spinBoxFeatureAngle = QtGui.QDoubleSpinBox(self.groupBox)
        self.spinBoxFeatureAngle.setDecimals(1)
        self.spinBoxFeatureAngle.setProperty("value", 1.0)
        self.spinBoxFeatureAngle.setObjectName("spinBoxFeatureAngle")
        self.horizontalLayout_2.addWidget(self.spinBoxFeatureAngle)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabCurves)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioRubberAngle = QtGui.QRadioButton(self.groupBox_2)
        self.radioRubberAngle.setChecked(True)
        self.radioRubberAngle.setObjectName("radioRubberAngle")
        self.horizontalLayout_3.addWidget(self.radioRubberAngle)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.spinBoxRubberAngle = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxRubberAngle.setDecimals(1)
        self.spinBoxRubberAngle.setProperty("value", 5.0)
        self.spinBoxRubberAngle.setObjectName("spinBoxRubberAngle")
        self.horizontalLayout_3.addWidget(self.spinBoxRubberAngle)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabCurves, "")
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName("tab2")
        self.tabWidget.addTab(self.tab2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(CadSettings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), CadSettings.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), CadSettings.accept)
        QtCore.QMetaObject.connectSlotsByName(CadSettings)

    def retranslateUi(self, CadSettings):
        CadSettings.setWindowTitle(QtGui.QApplication.translate("CadSettings", "CadTools Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("CadSettings", "Feature Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.radioFeaturePitch.setText(QtGui.QApplication.translate("CadSettings", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxFeaturePitch.setPrefix(QtGui.QApplication.translate("CadSettings", "Millimeter(s) ", None, QtGui.QApplication.UnicodeUTF8))
        self.radioFeatureAngle.setText(QtGui.QApplication.translate("CadSettings", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxFeatureAngle.setPrefix(QtGui.QApplication.translate("CadSettings", "Degree(s) ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("CadSettings", "Rubberband Segmentation", None, QtGui.QApplication.UnicodeUTF8))
        self.radioRubberAngle.setText(QtGui.QApplication.translate("CadSettings", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxRubberAngle.setPrefix(QtGui.QApplication.translate("CadSettings", "Degree(s) ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCurves), QtGui.QApplication.translate("CadSettings", "Arcs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), QtGui.QApplication.translate("CadSettings", "...", None, QtGui.QApplication.UnicodeUTF8))

