# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orthogonaltraverse.ui'
#
# Created: Sat Jun 12 21:24:01 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_OrthogonalTraverse(object):
    def setupUi(self, OrthogonalTraverse):
        OrthogonalTraverse.setObjectName("OrthogonalTraverse")
        OrthogonalTraverse.resize(548, 237)
        self.gridLayout = QtGui.QGridLayout(OrthogonalTraverse)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblStartPnt = QtGui.QLabel(OrthogonalTraverse)
        self.lblStartPnt.setObjectName("lblStartPnt")
        self.verticalLayout.addWidget(self.lblStartPnt)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblEndPnt = QtGui.QLabel(OrthogonalTraverse)
        self.lblEndPnt.setObjectName("lblEndPnt")
        self.verticalLayout_2.addWidget(self.lblEndPnt)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblEndX = QtGui.QLabel(OrthogonalTraverse)
        self.lblEndX.setObjectName("lblEndX")
        self.horizontalLayout_3.addWidget(self.lblEndX)
        self.lineEditEndX = QtGui.QLineEdit(OrthogonalTraverse)
        self.lineEditEndX.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditEndX.setObjectName("lineEditEndX")
        self.horizontalLayout_3.addWidget(self.lineEditEndX)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lblEndY = QtGui.QLabel(OrthogonalTraverse)
        self.lblEndY.setObjectName("lblEndY")
        self.horizontalLayout_3.addWidget(self.lblEndY)
        self.lineEditEndY = QtGui.QLineEdit(OrthogonalTraverse)
        self.lineEditEndY.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditEndY.setObjectName("lineEditEndY")
        self.horizontalLayout_3.addWidget(self.lineEditEndY)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayoutTraverse = QtGui.QHBoxLayout()
        self.horizontalLayoutTraverse.setObjectName("horizontalLayoutTraverse")
        self.lblPntTraverse = QtGui.QLabel(OrthogonalTraverse)
        self.lblPntTraverse.setObjectName("lblPntTraverse")
        self.horizontalLayoutTraverse.addWidget(self.lblPntTraverse)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutTraverse.addItem(spacerItem1)
        self.lineEditTraverse = QtGui.QLineEdit(OrthogonalTraverse)
        self.lineEditTraverse.setObjectName("lineEditTraverse")
        self.horizontalLayoutTraverse.addWidget(self.lineEditTraverse)
        self.gridLayout_2.addLayout(self.horizontalLayoutTraverse, 3, 0, 1, 2)
        self.horizontalLayoutFs = QtGui.QHBoxLayout()
        self.horizontalLayoutFs.setObjectName("horizontalLayoutFs")
        self.lblFs = QtGui.QLabel(OrthogonalTraverse)
        self.lblFs.setObjectName("lblFs")
        self.horizontalLayoutFs.addWidget(self.lblFs)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutFs.addItem(spacerItem2)
        self.lineEditFs = QtGui.QLineEdit(OrthogonalTraverse)
        self.lineEditFs.setEnabled(True)
        self.lineEditFs.setReadOnly(True)
        self.lineEditFs.setObjectName("lineEditFs")
        self.horizontalLayoutFs.addWidget(self.lineEditFs)
        self.gridLayout_2.addLayout(self.horizontalLayoutFs, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.btnEql = QtGui.QPushButton(OrthogonalTraverse)
        self.btnEql.setObjectName("btnEql")
        self.horizontalLayout_4.addWidget(self.btnEql)
        self.btnOK = QtGui.QPushButton(OrthogonalTraverse)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout_4.addWidget(self.btnOK)
        self.btnCancel = QtGui.QPushButton(OrthogonalTraverse)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_4.addWidget(self.btnCancel)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblStartX = QtGui.QLabel(OrthogonalTraverse)
        self.lblStartX.setObjectName("lblStartX")
        self.horizontalLayout_2.addWidget(self.lblStartX)
        self.lineEditStartX = QtGui.QLineEdit(OrthogonalTraverse)
        self.lineEditStartX.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditStartX.setText("")
        self.lineEditStartX.setObjectName("lineEditStartX")
        self.horizontalLayout_2.addWidget(self.lineEditStartX)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.lblStartY = QtGui.QLabel(OrthogonalTraverse)
        self.lblStartY.setObjectName("lblStartY")
        self.horizontalLayout_2.addWidget(self.lblStartY)
        self.lineEditStartY = QtGui.QLineEdit(OrthogonalTraverse)
        self.lineEditStartY.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEditStartY.setObjectName("lineEditStartY")
        self.horizontalLayout_2.addWidget(self.lineEditStartY)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxStartEnd = QtGui.QCheckBox(OrthogonalTraverse)
        self.checkBoxStartEnd.setEnabled(False)
        self.checkBoxStartEnd.setObjectName("checkBoxStartEnd")
        self.horizontalLayout.addWidget(self.checkBoxStartEnd)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(OrthogonalTraverse)
        QtCore.QMetaObject.connectSlotsByName(OrthogonalTraverse)

    def retranslateUi(self, OrthogonalTraverse):
        OrthogonalTraverse.setWindowTitle(QtGui.QApplication.translate("OrthogonalTraverse", "Orthogonal Traverse", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStartPnt.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Starting Point: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndPnt.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Endpoint: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndX.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Easting: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndY.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Northing: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPntTraverse.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Traverse: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFs.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Fs: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEql.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Equalisation", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOK.setText(QtGui.QApplication.translate("OrthogonalTraverse", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStartX.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Easting: ", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStartY.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Northing: ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxStartEnd.setText(QtGui.QApplication.translate("OrthogonalTraverse", "Startpoint = Endpoint", None, QtGui.QApplication.UnicodeUTF8))

